### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [snowflakelinux/icicle#1]
https://hosted.weblate.org/projects/snowflakeos/icicle/#information is GPLv3-only,
but I don't see a purpose in specifying this limitation when the source repo doesn't.
Going GPLv3-or-later (GPLv3+) allows deciding whether any newer version of the license is better once released.

**Comment by vlinkz** [comment]
The metadata for the project does specify GPLv3-only here: [org.snowflakeos.Icicle.metainfo.xml.in.in](https://github.com/snowflakelinux/icicle/blob/main/data/org.snowflakeos.Icicle.metainfo.xml.in.in#L5), so I set the translation license to reflect that, there might be a discussion to be had about licensing under GPLv3+ vs GPLv3-only though

**Comment by comradekingu** [comment]
Would be better to get that sorted without having to ask many translators.

**Comment by vlinkz** [comment]
Good point, better to finalize it now. I re-read the license details and changed it to now specify GPLv3-or-later to have greater compatibility with other GPL licenses in the future. I updated the specification on weblate as well.
